apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Hello@123"
    - name: MYSQL_DATABASE
      value: "B-Hak_Sengkea-db"